
import React from 'react';
import { Story } from '../types';
import { Star, Book } from 'lucide-react';

interface LibraryProps {
  stories: Story[];
  onSelectStory: (story: Story) => void;
}

const colorVariants: Record<string, string> = {
  green: 'bg-green-100 hover:bg-green-200 border-green-200 text-green-800',
  orange: 'bg-orange-100 hover:bg-orange-200 border-orange-200 text-orange-800',
  blue: 'bg-blue-100 hover:bg-blue-200 border-blue-200 text-blue-800',
  teal: 'bg-teal-100 hover:bg-teal-200 border-teal-200 text-teal-800',
  purple: 'bg-purple-100 hover:bg-purple-200 border-purple-200 text-purple-800',
  red: 'bg-red-100 hover:bg-red-200 border-red-200 text-red-800',
};

const iconBgVariants: Record<string, string> = {
  green: 'bg-green-200',
  orange: 'bg-orange-200',
  blue: 'bg-blue-200',
  teal: 'bg-teal-200',
  purple: 'bg-purple-200',
  red: 'bg-red-200',
};

export const Library: React.FC<LibraryProps> = ({ stories, onSelectStory }) => {
  return (
    <div className="min-h-screen bg-[#f8fafc] p-6 md:p-10 font-['Fredoka']">
      <div className="max-w-6xl mx-auto">
        <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-12">
            <div className="flex items-center gap-4">
                <div className="bg-yellow-400 p-3 rounded-2xl shadow-[0_4px_0_rgb(202,138,4)]">
                    <Book className="w-8 h-8 text-yellow-900" />
                </div>
                <div>
                    <h1 className="text-4xl font-black text-slate-800 tracking-tight">Panchatantra Tales</h1>
                    <p className="text-slate-500 font-medium">Pick a story to start your adventure!</p>
                </div>
            </div>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {stories.map((story) => {
            const cardClass = colorVariants[story.color] || colorVariants.green;
            const iconClass = iconBgVariants[story.color] || iconBgVariants.green;

            return (
              <button
                key={story.id}
                onClick={() => onSelectStory(story)}
                className={`
                  group relative p-6 rounded-3xl border-b-8 transition-all duration-300
                  transform hover:-translate-y-2 hover:shadow-xl text-left flex flex-col h-full
                  ${cardClass}
                `}
              >
                <div className="flex items-start justify-between mb-4">
                  <div className={`w-16 h-16 rounded-2xl ${iconClass} flex items-center justify-center text-4xl shadow-inner`}>
                    {story.icon}
                  </div>
                  <Star className="text-yellow-400 fill-current w-6 h-6 opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>
                
                <h2 className="text-2xl font-black mb-2 leading-tight group-hover:scale-[1.02] transition-transform origin-left">
                  {story.title}
                </h2>
                
                <p className="mt-auto pt-4 text-sm font-bold opacity-60 uppercase tracking-widest">
                  Read Now →
                </p>
              </button>
            );
          })}
        </div>
        
        <div className="mt-16 text-center">
            <p className="text-slate-400 font-bold text-sm">
                Generated by Swapan Roy
            </p>
        </div>
      </div>
    </div>
  );
};
